name: Build and Deploy Web App

# source: https://gist.github.com/rodydavis/bde9a9a8c2fcdcf3474c0f50248f2e3a

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
    - uses: actions/checkout@v1
    - run: ls -lah
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: flutter pub get
    - run: flutter config --enable-web
    - run: flutter build web
    - run: ls -lah
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: app/build/web # The folder the action should deploy.
