name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - server/**
  pull_request:
    branches: [ master ]
    paths:
      - server/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file server/Dockerfile --tag singaltanmay/flutter-notes-server:$(date +%s)
