name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: List Code Root Directory
      run: ls -lah
    - name: Enter the server directory
      run: cd server
    - name: List server Directory
      run: ls -lah
    - name: Build the Docker image
      run: docker build --tag singaltanmay/flutter-notes-server:$(date +%s) .
