name: Server Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: ./server
      run: ls -lah && docker build --tag singaltanmay/flutter-notes-server:$(date +%s) .
