name: Server Docker Image CI

on:
  push:
    branches: [ master ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          src:
            - 'server/**'
      
    - name: Check for any changes in server/ folder
      run: if [[ {{steps.changes.outputs.src}} == 'false' ]]; then \
            echo 'There are no changes in the server/ folder. Exiting' \
            exit 0 ; fi
          
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./server
        push: true
        tags: echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        labels: ${{ steps.meta.outputs.labels }}
