name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Enter the server directory
      run: cd server/
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag singaltanmay/flutter-notes-server:$(date +%s)
